#PÃ¡gina de inÃ­cio
[[pages]]
path = "src/home.py"
name = "InÃ­cio"
icon = "ğŸ "

[[pages]]
name = "ConfiguraÃ§Ãµes"
icon = "ğŸ› "
is_section = true

[[pages]]
name = "ConfiguraÃ§Ãµes"
path = "src/settings.py"
icon = "âš™"

[[pages]]
name = "Conta"
path = "src/conta.py"
icon = "ğŸ¤“"